app:
  couchbase:
    connection-string: couchbase://127.0.0.1
    user-name: Administrator
    password: SOME_AWESOME_PASSWORD_HERE
    bucket-PIES: PRODUCTS
    bucket-ACES: CATALOG

logging:
  level:
    org:
      hibernate:
        type: trace